apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-idp-1-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pe-idp-1
  template:
    metadata:
      labels:
        app: pe-idp-1
    spec:
      containers:
      - name: app
        image: gcr.io/your-project-id/pe-idp-1-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pe-idp-1-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: pe-idp-1
